### PR TITLE
[FEATURE] Add the ability to allow all processes to die

### PR DESCRIPTION
**Pull request by maschwenk**
I like to run things daemonized and move around projects. I generally don't like my processes to ever kill overmind because it makes daemonized mode annoying (you try to make a change to a process and suddenly overmind isn't even running).

~I haven't yet built this locally so fair warning.~ Built it locally and seems to work

### CODE REVIEW

**Comment by maschwenk** [comment]
@DarthSim Thoughts on this change?

**Comment by synthead** [comment]
This would be really useful :)

**Comment by DarthSim** [comment]
Looks good! Thanks for your contribution!

**Comment by maschwenk** [comment]
@DarthSim I'm not actually able to see this option when I run `overmind start --any-can-die`

**Pull request merged**
